In [6]:
import pandas as pd
cbio3 = pd.read_csv('SolCbio3Database_merged.csv')
mp = pd.read_csv('mp_pubchem.csv')
logp = pd.read_csv('logp_pubchem.csv')

In [7]:
cbio3_missing_mp = cbio3[cbio3['mp'].isnull()].copy()
cbio3_missing_logp = cbio3[cbio3['logPN'].isnull()].copy()

In [8]:
is_present_mp = cbio3_missing_mp['SMILES_standard'].isin(logp['SMILES_standard'])
is_present_logp = cbio3_missing_logp['SMILES_standard'].isin(logp['SMILES_standard'])

In [13]:
cbio3_missing_logp_with_logp = cbio3_missing_logp[is_present_logp].copy()
merged_logp = pd.merge(cbio3_missing_logp_with_logp[['SMILES_standard']],
                       logp[['SMILES_standard']],
                       on='SMILES_standard',
                       how='left')

cbio3.loc[cbio3_missing_logp_with_logp.index, 'Ref_logP'] = "PubChem"

cbio3.loc[cbio3_missing_logp_with_logp.index]

,id,Compound,smiles,CAS_RN,logS,pH,Ref_logS,mp,Ref_mp,logPN,Ref_logP,SMILES_standard
1,SolCbio3-2,Octacholodibenzo-p-dioxin,Clc1c(Cl)c(Cl)c2c(c1Cl)Oc1c(Cl)c(Cl)c(Cl)c(Cl)...,3268-87-9,-12.790000,NaN,1,322.0,1,NaN,PubChem,Clc1c(Cl)c(Cl)c2c(c1Cl)Oc1c(Cl)c(Cl)c(Cl)c(Cl)...
43,SolCbio3-44,1-Octadecanol,CCCCCCCCCCCCCCCCCCO,112-92-5,-8.400000,NaN,1,61.0,1,NaN,PubChem,CCCCCCCCCCCCCCCCCCO
104,SolCbio3-105,"2,2',3,3',4-Pentachlorobiphenyl",Clc1cccc(-c2ccc(Cl)c(Cl)c2Cl)c1Cl,52663-62-4,-7.050000,NaN,1,119.0,1,NaN,PubChem,Clc1cccc(-c2ccc(Cl)c(Cl)c2Cl)c1Cl
146,SolCbio3-147,Dieldrin,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,60-57-1,-6.290000,NaN,1,175.0,1,NaN,PubChem,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl
162,SolCbio3-163,Tricresyl-phosphate,Cc1ccc(OP(=O)(Oc2ccc(C)cc2)Oc2ccc(C)cc2)cc1,1330-78-5,-6.010000,NaN,1,-33.0,1,NaN,PubChem,Cc1ccc(OP(=O)(Oc2ccc(C)cc2)Oc2ccc(C)cc2)cc1
...,...,...,...,...,...,...,...,...,...,...,...,...
4356,SolCbio3-4357,F-460,CCCCCCCOC(=O)C1=C(C=CC=C1)C(=O)OCCCCCCC,NaN,-8.560000,NaN,AqSolDB,NaN,NaN,NaN,PubChem,CCCCCCCOC(=O)c1ccccc1C(=O)OCCCCCCC
4513,SolCbio3-4514,Sulfenone,O=S(=O)(c1ccccc1)c1ccc(Cl)cc1,80-00-2,-3.388975,NaN,BigSolDB2.0,NaN,NaN,NaN,PubChem,O=S(=O)(c1ccccc1)c1ccc(Cl)cc1
4523,SolCbio3-4524,Uridine,O=c1ccn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c(=O...,58-96-8,0.369720,NaN,BigSolDB2.0,NaN,NaN,NaN,PubChem,O=c1ccn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c(=O...
4538,SolCbio3-4539,Moxidectin,CO/N=C1\C[C@]2(C[C@@H]3C[C@@H](C/C=C(\C)C[C@@H...,113507-06-5,-3.222284,NaN,BigSolDB2.0,NaN,NaN,NaN,PubChem,CO/N=C1\C[C@]2(C[C@@H]3C[C@@H](C/C=C(\C)C[C@@H...
4548,SolCbio3-4549,Dimethyl fumarate,COC(=O)/C=C/C(=O)OC,624-49-7,-2.289940,NaN,BigSolDB2.0,NaN,NaN,NaN,PubChem,COC(=O)/C=C/C(=O)OC

In [14]:
cbio3_missing_mp_with_mp = cbio3_missing_mp[is_present_mp].copy()
merged_mp = pd.merge(cbio3_missing_mp_with_mp[['SMILES_standard']],
                       mp[['SMILES_standard']],
                       on='SMILES_standard',
                       how='left')

cbio3.loc[cbio3_missing_mp_with_mp.index, 'Ref_mp'] = "PubChem"

cbio3.loc[cbio3_missing_mp_with_mp.index]

,id,Compound,smiles,CAS_RN,logS,pH,Ref_logS,mp,Ref_mp,logPN,Ref_logP,SMILES_standard
1225,SolCbio3-1226,A-10,CC1=CC=CC(C=C)=C1,NaN,-3.123150,NaN,AqSolDB,NaN,PubChem,NaN,PubChem,C=Cc1cccc(C)c1
1235,SolCbio3-1236,A-29,CC(C)=C1CCC(C)=CC1,NaN,-4.287343,NaN,AqSolDB,NaN,PubChem,4.47,Kenneth,CC1=CCC(=C(C)C)CC1
1237,SolCbio3-1238,A-36,CC1(C)C2CC1C(=C)CC2,NaN,-4.292313,NaN,AqSolDB,NaN,PubChem,4.16,Kenneth,C=C1CCC2CC1C2(C)C
1243,SolCbio3-1244,A-58,CC1=CC=C(C=C1)C(C)(C)C,NaN,-4.472022,NaN,AqSolDB,NaN,PubChem,5.17,Kenneth,Cc1ccc(C(C)(C)C)cc1
1244,SolCbio3-1245,A-70,CC12OC1CC1CC2C1(C)C,NaN,-2.593688,NaN,AqSolDB,NaN,PubChem,NaN,PubChem,CC1(C)C2CC3OC3(C)C1C2
...,...,...,...,...,...,...,...,...,...,...,...,...
4540,SolCbio3-4541,Modafinil,NC(=O)CS(=O)C(c1ccccc1)c1ccccc1,68693-11-8,-2.348725,NaN,BigSolDB2.0,NaN,PubChem,0.60,Kenneth,NC(=O)C[S+]([O-])C(c1ccccc1)c1ccccc1
4542,SolCbio3-4543,Deferiprone,Cc1c(O)c(=O)ccn1C,30652-11-0,-0.899863,NaN,BigSolDB2.0,NaN,PubChem,-0.77,Kenneth,Cc1c(O)c(=O)ccn1C
4548,SolCbio3-4549,Dimethyl fumarate,COC(=O)/C=C/C(=O)OC,624-49-7,-2.289940,NaN,BigSolDB2.0,NaN,PubChem,NaN,PubChem,COC(=O)/C=C/C(=O)OC
4555,SolCbio3-4556,Phenylethanal,O=CCc1ccccc1,122-78-1,-1.004805,NaN,BigSolDB2.0,NaN,PubChem,1.78,Kenneth,O=CCc1ccccc1
4558,SolCbio3-4559,5-fluorouracil,O=c1[nH]cc(F)c(=O)[nH]1,51-21-8,-0.860686,NaN,BigSolDB2.0,NaN,PubChem,-0.89,Kenneth,O=c1[nH]cc(F)c(=O)[nH]1

In [15]:
cbio3.to_csv('SolCbio3Database_merged2.csv')